# Generated by Django 5.2.3 on 2025-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved_organizer',
        ),
        migrations.AddField(
            model_name='grouprole',
            name='can_manage_leadership',
            field=models.BooleanField(default=False),
        ),
    ]
