# Generated by Django 5.2.3 on 2025-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_approved_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID for authentication', null=True, unique=True),
        ),
    ]
