# Generated by Django 5.2.3 on 2025-06-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_post_alter_rsvp_options_event_address_and_more'),
        ('users', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use GroupRole instead', to='events.group'),
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('founder', 'Founder'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('event_manager', 'Event Manager'), ('helper', 'Helper')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('custom_label', models.CharField(blank=True, help_text='Custom label for this leader (optional)', max_length=64, null=True)),
                ('can_post', models.BooleanField(default=False, help_text='Can this user make posts for the group?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='events.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Role',
                'verbose_name_plural': 'Group Roles',
                'ordering': ['role_name', 'assigned_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
