# Generated by Django 5.2.3 on 2025-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_event_name_alter_banneduser_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouprole',
            options={'ordering': ['assigned_at'], 'verbose_name': 'Group Role', 'verbose_name_plural': 'Group Roles'},
        ),
        migrations.RemoveField(
            model_name='grouprole',
            name='role_name',
        ),
        migrations.AddField(
            model_name='grouprole',
            name='is_tier',
            field=models.BooleanField(default=False, help_text='Tier (checked = yes, unchecked = no)'),
        ),
    ]
