# Generated by Django 5.2.4 on 2025-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post_blog',
            field=models.BooleanField(default=False, help_text='Can post blog posts to Bluesky'),
        ),
    ]
