# Generated by Django 5.2.3 on 2025-06-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_grouprole_options_remove_grouprole_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprole',
            name='is_tier',
        ),
    ]
