# Generated by Django 5.2.3 on 2025-06-18 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('original_link', models.URLField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(choices=[('none', 'All ages'), ('adult', '18+ (Adult)'), ('mature', '21+ (Mature)')], default='none', help_text='Age restriction for the event', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees. Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the event', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=False, help_text='Enable a waitlist if capacity is reached.'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the group', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the group and its activities'),
        ),
        migrations.AddField(
            model_name='group',
            name='logo_base64',
            field=models.TextField(blank=True, help_text='Group logo as base64 string', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_channel',
            field=models.CharField(blank=True, help_text='Telegram channel username (without @)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, help_text="Group's website URL", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('maybe', 'Maybe'), ('not_attending', 'Not Attending')], default='confirmed', max_length=20, null=True),
        ),
    ]
